Repository guibranco/gstraccini-bot-service, pull requests merged in 2024-08, with the labels that each got.

#386 Update comments.php
  .github/workflows/build.yml
  Src/comments.php
Labels: size/S, ☑️ auto-merge

#388 Update comments.php
  Src/comments.php
Labels: size/XS, ☑️ auto-merge

#389 Update pullRequests.php
  Src/pullRequests.php
Labels: size/XS, ☑️ auto-merge

#390 Update pullRequests.php
  Src/pullRequests.php
Labels: size/XS, ☑️ auto-merge

#391 Update pullRequests.php
  Src/pullRequests.php
Labels: size/XS, ☑️ auto-merge

#392 Update github.php
  Src/lib/github.php
Labels: size/XS, ☑️ auto-merge

#393 Update config.php
  Src/config/config.php
Labels: size/XS, ☑️ auto-merge

#394 Update database.php
  Src/lib/database.php
Labels: size/S, ☑️ auto-merge

#396 Update pullRequests.php
  Src/pullRequests.php
Labels: size/S, ☑️ auto-merge

#398 Update config.php
  Src/config/config.php
Labels: size/S, ☑️ auto-merge

#399 Update pullRequests.php
  Src/pullRequests.php
Labels: size/XS, ☑️ auto-merge

#400 Update pullRequests.php
  Src/pullRequests.php
Labels: size/S, ☑️ auto-merge

#401 Update pullRequests.php
  Src/pullRequests.php
Labels: size/XS, ☑️ auto-merge

#402 Update pullRequests.php
  Src/pullRequests.php
Labels: size/XS, ☑️ auto-merge

#403 Update pullRequests.php
  Src/pullRequests.php
Labels: size/XS, ☑️ auto-merge

#404 Update pullRequests.php
  Src/pullRequests.php
Labels: size/XS, ☑️ auto-merge

#405 Update pullRequests.php
  Src/pullRequests.php
Labels: size/S, ☑️ auto-merge

#406 Update pullRequests.php
  Src/pullRequests.php
Labels: size/XS, ☑️ auto-merge

#407 Update pullRequests.php
  Src/pullRequests.php
Labels: size/XS, ☑️ auto-merge

#408 Update pullRequests.php
  Src/pullRequests.php
Labels: size/XS, ☑️ auto-merge

#409 Update pullRequests.php
  Src/pullRequests.php
Labels: size/XS, ☑️ auto-merge

#410 Update pullRequests.php
  Src/pullRequests.php
Labels: size/XS, ☑️ auto-merge

#411 Update github.php
  Src/lib/github.php
Labels: size/S, ☑️ auto-merge

#412 Update pullRequests.php
  Src/pullRequests.php
Labels: size/XS, ☑️ auto-merge

#413 Update pullRequests.php
  Src/pullRequests.php
Labels: size/XS, ☑️ auto-merge

#414 Update pullRequests.php
  Src/pullRequests.php
Labels: size/XS, ☑️ auto-merge

#415 Update pullRequests.php
  Src/pullRequests.php
Labels: size/S, ☑️ auto-merge

#417 Update pullRequests.php
  Src/pullRequests.php
Labels: size/S, ☑️ auto-merge

#418 Update pullRequests.php
  Src/pullRequests.php
Labels: size/M, ☑️ auto-merge

#419 Create add-project-to-solution.yml
  .github/workflows/add-project-to-solution.yml
Labels: size/M, ☑️ auto-merge

#421 Update comments.php
  Src/comments.php
Labels: size/S, ☑️ auto-merge

#420 Update commands.json
  Src/config/commands.json
Labels: size/S, ☑️ auto-merge

#422 Update deploy.yml
  .github/workflows/deploy.yml
Labels: size/XS, ☑️ auto-merge

#423 Update comments.php
  Src/comments.php
Labels: size/XS, ☑️ auto-merge

#426 Update pullRequests.php
  Src/pullRequests.php
Labels: size/XS, ☑️ auto-merge

#427 Update comments.php
  Src/comments.php
Labels: size/XS, ☑️ auto-merge

#434 Update pullRequests.php
  Src/pullRequests.php
Labels: size/XS

#436 Update pullRequests.php
  Src/pullRequests.php
Labels: size/XS

#442 Update pullRequests.php
  Src/pullRequests.php
Labels: size/XS, ☑️ auto-merge

#444 Track repository creation
  .github/workflows/deploy.yml
  README.md
  Src/comments.php
  Src/config/commands.json
  Src/repositories.php
Labels: documentation, enhancement, size/L, database, PHP, new repository, ☑️ auto-merge

#445 Update repositories.php
  Src/repositories.php
Labels: size/XS, ☑️ auto-merge

#446 Update deploy.yml
  .github/workflows/deploy.yml
Labels: size/XS, ☑️ auto-merge

#447 Set HealthChecksIo User-Agent header
  Src/branches.php
  Src/comments.php
  Src/composer.json
  Src/composer.lock
  Src/issues.php
  Src/pullRequests.php
  Src/pushes.php
  Src/repositories.php
  Src/signature.php
Labels: size/M, ☑️ auto-merge

#448 Update pullRequests.php
  Src/pullRequests.php
Labels: size/S, ☑️ auto-merge

#449 Update pullRequests.php
  Src/pullRequests.php
Labels: size/M, ☑️ auto-merge

#455 Enhance pull request comment handling for dependabot
  Src/pullRequests.php
Labels: enhancement, size/XS, ☑️ auto-merge, Review effort [1-5]: 2

#456 Enhance issue handling by removing awaiting triage label for collaborators
  Src/issues.php
Labels: enhancement, size/S, ☑️ auto-merge, Review effort [1-5]: 3

#457 Improve git configuration in csharpier.yml
  .github/workflows/csharpier.yml
Labels: enhancement, size/XS, ☑️ auto-merge, Review effort [1-5]: 2

#458 Update Git Configuration in add-project-to-solution.yml
  .github/workflows/add-project-to-solution.yml
Labels: enhancement, size/XS, ☑️ auto-merge, Review effort [1-5]: 2

#461 Update git configuration in prettier.yml
  .github/workflows/prettier.yml
Labels: enhancement, size/XS, ☑️ auto-merge, Review effort [1-5]: 2

#459 Enhance CI workflow with additional test handlers
  .github/workflows/build.yml
Labels: enhancement, size/S, ☑️ auto-merge, Review effort [1-5]: 2

#460 Improve git configuration in csharpier.yml
  .github/workflows/csharpier.yml
Labels: enhancement, size/XS, ☑️ auto-merge, Review effort [1-5]: 2

#462 Improve Shellcheck command execution in workflow
  .github/workflows/shell-cheker.yml
Labels: enhancement, size/XS, ☑️ auto-merge, Review effort [1-5]: 1

#463 Improve update-test-snapshot.yml workflow configuration
  .github/workflows/update-test-snapshot.yml
Labels: enhancement, size/XS, ☑️ auto-merge, Review effort [1-5]: 2

#464 Update pullRequests.php
  Src/pullRequests.php
Labels: size/S, ☑️ auto-merge

#465 Enhance pull request handling and update logic
  Src/pullRequests.php
Labels: enhancement, size/S, ☑️ auto-merge, Review effort [1-5]: 3

#466 Improve JSON Decoding in pullRequests.php
  Src/pullRequests.php
Labels: enhancement, size/XS, ☑️ auto-merge, Review effort [1-5]: 2

#467 Enhance branch reference handling in pullRequests.php
  Src/pullRequests.php
Labels: enhancement, size/XS, ☑️ auto-merge, Review effort [1-5]: 2

#468 Enhance error handling in pullRequests.php
  Src/pullRequests.php
Labels: enhancement, size/XS, ☑️ auto-merge, Review effort [1-5]: 2

#469 Refactor label removal in issues.php for better functionality
  Src/issues.php
Labels: enhancement, size/S, ☑️ auto-merge, Review effort [1-5]: 2

#470 Refactor User-Agent Header Handling Across Multiple Files
  Src/branches.php
  Src/comments.php
  Src/config/config.php
  Src/issues.php
  Src/lib/appveyor.php
  Src/lib/github.php
  Src/lib/queue.php
  Src/pullRequests.php
  Src/pushes.php
  Src/repositories.php
  Src/signature.php
Labels: enhancement, size/S, ☑️ auto-merge, Review effort [1-5]: 2

#471 Add issue copying feature between repositories
  Src/comments.php
  Src/config/commands.json
Labels: enhancement, size/M, ☑️ auto-merge, Review effort [1-5]: 4

#472 Update URL structure for GitHub issue labels
  Src/issues.php
Labels: enhancement, size/XS, ☑️ auto-merge, Review effort [1-5]: 2

#473 Enhance regex pattern in comments.php for issue copying
  Src/comments.php
Labels: enhancement, size/XS, Review effort [1-5]: 2

#474 Enhance error handling and repository URL construction in comments.php
  Src/comments.php
Labels: enhancement, size/S, Review effort [1-5]: 2

#475 Enhance pull request status checking in comments.php
  Src/comments.php
Labels: enhancement, size/XS, ☑️ auto-merge, Review effort [1-5]: 2

#476 Enhance comments handling and issue management in comments.php
  Src/comments.php
Labels: enhancement, size/M, ☑️ auto-merge, Review effort [1-5]: 3

#477 Enhance issue copying functionality in comments.php
  Src/comments.php
Labels: enhancement, size/XS, ☑️ auto-merge, Review effort [1-5]: 2

#478 Enhance comment handling for additional bot support
  Src/comments.php
Labels: enhancement, size/XS, ☑️ auto-merge, Review effort [1-5]: 2

#479 Enhance issue handling in issues.php
  Src/issues.php
Labels: enhancement, size/XS, ☑️ auto-merge, Review effort [1-5]: 2

#480 Fix typo in comments.php for PullRequestNumber
  Src/comments.php
Labels: enhancement, size/XS, ☑️ auto-merge, Review effort [1-5]: 1

#481 Enhance issue handling for private repositories
  Src/issues.php
Labels: enhancement, size/XS, ☑️ auto-merge, Review effort [1-5]: 2

#482 Enhance comments handling in comments.php
  Src/comments.php
Labels: enhancement, size/S, ☑️ auto-merge, Review effort [1-5]: 2

#484 Update comment posting URL in comments.php
  Src/comments.php
Labels: enhancement, size/XS, Review effort [1-5]: 2

#489 Update character set and collation for GitHub signature table
  Sql/004.create_github_signature_table.sql
Labels: enhancement, size/XS, ☑️ auto-merge, Review effort [1-5]: 1

#486 Rename and enhance GitHub comments table SQL script
  Sql/003.create_github_comments_table.sql
Labels: enhancement, size/XS, ☑️ auto-merge, Review effort [1-5]: 2

#487 Update character set and collation for GitHub issues table
  Sql/001.create_github_issues_table.sql
Labels: enhancement, size/XS, ☑️ auto-merge, Review effort [1-5]: 1

#490 Update comments table reference in comments.php
  Src/comments.php
Labels: enhancement, size/XS, ☑️ auto-merge, Review effort [1-5]: 2

#488 Enhance character set and collation for GitHub pull requests table
  Sql/002.create_github_pull_requests_table.sql
Labels: enhancement, size/XS, ☑️ auto-merge, Review effort [1-5]: 2
